Dashboard/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Dashboard.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Dashboard/Controllers/TemperatureController.cs
using Dashboard.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WoodStove.Core;

namespace Dashboard.Controllers
{
    [Authorize]
    public class TemperatureController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        // GET: Temperature
        public async Task<ActionResult> Index()
        {
            var dvm = new DevicesViewModel();

            dvm.Devices = await GetUserDevices().ToListAsync();

            return View(dvm);
        }

        private IQueryable<Device> GetUserDevices()
        {
            var userId = this.User.Identity.GetUserId();
            IQueryable<Device> devices = this.db.Users.Include(u => u.Devices).Where(u => u.Id == userId).SelectMany(u => u.Devices);
            return devices;
        }

        // GET: Temperature
        [AllowAnonymous]
        public async Task<ActionResult> Demo()
        {
            var dvm = new DevicesViewModel();

            var demoDevices = new List<Device>()
            {
                new Device()
                {
                    Id= "demo-1",
                    Name= "Demo",
                    ZipCode="92118",
                    Display = true
                }
            };

            dvm.Devices = demoDevices;

            return View("Index", dvm);
        }
    }

   
}

Dashboard/Views/Home/About.cshtml
@{
    ViewBag.Title = "Temprature";
}

<div class="row">
    <div class="col-sm-4 text-center">
        <h1 class="">Current Temp</h1>
        <span id="temp">0</span>

        <canvas id="mycanvas" width="400" height="100"></canvas>
    </div>
</div>

@section scripts
{
    <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>
    <script src="~/Scripts/smoothie.js"></script>
    
    <script>
        $(function () {
            var smoothie = new SmoothieChart();
            smoothie.streamTo(document.getElementById("mycanvas"));
            var line1 = new TimeSeries();
            smoothie.addTimeSeries(line1);

            // Declare a proxy to reference the hub.
            var tempHub = $.connection.tempHub;
            var currentDevice;

            tempHub.client.currentTemp = function (temp) {
                $('#temp').html(temp);
                line1.append(new Date().getTime(), temp);
            };

            $.connection.hub.start();
        });
    </script>
}

Dashboard/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>

<p>
    A wood stove monitoring system built using ASP.NET MVC on Azure with Eventhubs, StreamAnalytics, and SignalR.  If you have any questions please see my contact information below.
</p>

<p>
    <strong>Source:</strong> <a href="https://github.com/jsturtevant/woodstove">https://github.com/jsturtevant/woodstove</a><br />
    <strong>Blog:</strong> <a href="http://www.jamessturtevant.com/">http://www.jamessturtevant.com/</a><br />
</p>

<address>
    <strong>Contact:</strong>   <a href="mailto:jsturtevant@example.com">jsturtevant@gmail.com</a><br />
    <strong>Twitter:</strong> <a href="https://twitter.com/Aspenwilder">@@aspenwilder</a>
</address>

Dashboard/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    ViewBag.PageClass = "landing";
}

<div class="row">
    <div class="col-md-8">
        <h2>Monitor your stove from anywhere.</h2>
        <p>Whether you are in another room or half way accross the world you keep track of the temperate of your stove.  You can compare the tempratures of the stove to inside tempratures and outside tempratures allowing for you to burn more efficeintly and save money.</p>

        @if (!Request.IsAuthenticated)
        {
            <p>
                @Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink", @class = "btn btn-default" })
            </p>
            <p>Or</p>
            <p>
                @Html.ActionLink("See a Demo", "Demo", "Temperature", routeValues: null, htmlAttributes: new { id = "demo", @class = "btn btn-default" })
            </p>
        }
        else
        {
            <p>
                @Html.ActionLink("See your devices", "Index", "Temperature", routeValues: null, htmlAttributes: new { id = "demo", @class = "btn btn-default" })
            </p>
        }
    </div>
</div>